### ISSUE TITLE
ingestion not working because of missing "from" parameter when building the live stream url

### ISSUE THREAD

**Issue by benroussille** [OpenCTI-Platform/splunk-add-on#7]
### Description

When trying to configure the app on splunk, it cannot retrieve any data from OpenCTI. The requests are generating an HTTP 500 server error reply. 

### Environment

OpenCTI docker 6.3.6

### Reproducible Steps

1. Create a Live data stream on OpenCTI
2. Try to ingest it using the app on splunk
3. Check your logs

### Expected Output

Normal configuration of stream would work.

### Actual output

The stream is not working and generates the following log entry on the OpenCTI server:
`ERR
Recovery mode is only possible with a start date. | category=APP errors=[{"attributes":{"genre":"BUSINESS","http_status":500},"message":"Recovery mode is only possible with a start date.","name":"UNSUPPORTED_ERROR","stack":"GraphQLError: Recovery mode is only possible with a start date.\n    at error (/opt/opencti/build/src/config/errors.js:7:10)\n    at UnsupportedError (/opt/opencti/build/src/config/errors.js:88:51)\n    at fn (/opt/opencti/build/src/graphql/sseMiddleware.js:566:15)\n    at Rge.handle [as handle_request] (/opt/opencti/build/node_modules/express/lib/router/layer.js:95:5)\n    at next (/opt/opencti/build/node_modules/express/lib/router/route.js:149:13)\n    at authenticateForPublic (/opt/opencti/build/src/graphql/sseMiddleware.js:196:5)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)"}] id=c7b73c86-a283-47e7-8ded-7c467e16c6f9 source=backend timestamp=2024-10-17T12:15:25.604Z type=live version=6.3.6`

### Additional information

The code that generates this error in OpenCTI is located in opencti-platform/opencti-graphql/src/graphql/sseMiddleware.js and is as follow:

<img width="603" alt="image" src="https://github.com/user-attachments/assets/df3e11f6-71c5-4948-b7e7-c1f4cfc54dcd">

On the splunk app side, the live_stream_url is built as follow:

<img width="716" alt="image" src="https://github.com/user-attachments/assets/3b89a23f-7022-4684-b3fb-87d37aec92c4">

And then queried with the following headers:

<img width="444" alt="image" src="https://github.com/user-attachments/assets/b265081c-6749-43b8-923f-e1f31912bcc5">

We can clearly see that there is no "from" parameter hence generating the HTTP 500 error mentioned above.

**Comment by romain-filigran** [comment]
Hello @benroussille, what is the configuration of your "data inputs" and more specifically what is the value associated to the "Import from (days)" parameter ?
It's this setting that will generate a start_from date. 
Can you share some logs generated by the Splunk App and more exactly the log starting by  "checkpoint State:" 

![Capture d'écran 2024-10-21 092127](https://github.com/user-attachments/assets/76de232b-a7b1-4e54-b799-8b8fe52996d0)

**Comment by benroussille** [comment]
Hello @romain-filigran, please find hereby the requested info:

![image](https://github.com/user-attachments/assets/22aba069-28c3-4a32-86c9-f4237e28d5ac)
The Import from is set to 90 days

And here is a screenshot of some logs:
![image](https://github.com/user-attachments/assets/b3446bea-551c-427f-ab1b-ffcf631fbb65)

**Comment by romain-filigran** [comment]
Hello. I was not able to reproduce your problem. In fact, this 500 error could happen when we trying to consume the stream with a recover parameter and without a "from" parameter in the URL or a "Last-Event-ID" header but it seems not to be the case as your log demonstrate that the state is correctly set and contains a value for "start_from". Can you confirm that no indicators are ingested in your platform and that you observed this 500 error at each connection ? 

If yes, can you try to disable this data input and to create a new one with a different name.

**Comment by romain-filigran** [comment]
Hello @benroussille : Do you have any update on this issue ?

**Comment by benroussille** [comment]
Hello @romain-filigran my apologies for the delay. We decided to uninstall the app and to reinstall a vanilla version directly from the github code (instead of splunk base). And we indeed have the normal behavior and are able to ingest the feed properly. 
We still do not know what went wrong during the first installation but it looks like the issue has been resolved by reinstalling the app.
